<CameraView>:
    orientation: 'vertical'
    GridLayout:
        rows: 1
        row_force_default: True
        row_default_height: 20
        cols: 4
        size_hint: (1,1)
        Button:
            text: 'Configs'
        Button:
            text: 'Configs'
        Button:
            text: 'Configs'
        Button:
            text: 'Configs'
    Camera:
        id: camera
        resolution: (1920,1080)
        play: True